# Runs Ruff, Black and Pytest before every one commit.

repos:

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Black
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
      
      - id: black-jupyter
        language_version: python3.12
  
  # Pytest
  # - repo: https://github.com/christophmeissner/pytest-pre-commit
  #   rev: 1.0.0
  #   hooks:
  #   - id: pytest
  #     pass_filenames: false
  #     always_run: true