# Runs Ruff, Black and Pytest before every one commit.

repos:
  
  # Ruff 
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: ["--fix"]

  # Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:  
      - id: black
        args: ["--line-length=88"]
